name: Deploy to Cloud Run

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Configure Docker to use gcloud as credential helper
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
        gcloud auth login

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: classification-service
        push: true
        tags: us-central1-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/email-automation-repo/classification-api:latest

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: ${{ secrets.GCP_SERVICE_NAME }}
        image: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/email-automation-repo/classification-api:latest
        region: ${{ secrets.GCP_REGION }}